# name: "Mirror ${{ github.event.inputs.image }} to ${{ github.event.inputs.registry }}"
name: "Mirror image"

on:
  workflow_dispatch:
    inputs:
        image:
          description: |
            The name of the image to mirror, e.g. alpine, or efrecon/reg-tags. When a
            tag is specified, the inputs `tags`, `minver` and `maxver` are ignored.
          required: true
          type: string
          # default: 'latest'
        registry:
          description: |
            The path of the destination registry. The default is to pick the GHCR and
            reroot under the repository.
          required: true
          type: string
          default: "ghcr.io/someorg/somerepo"
        options:
          description: |
            Additional options to `mirror.sh` script, e.g. -f to force re-creation of
            destination images that would already exist. This is a semi-internal input
            and should only be used for debugging.
          required: false
          type: string
          default: "-v"
        tags:
          description: |
            Regular expression to match against the tags of source image so they will
            be considered for mirroring. Only used when `image` does not contain a
            tag.
          required: true
          type: string
          default: '[0-9]+(\.[0-9]+)+$'
        minver:
          description: |
            Minimal version (extracted from image tag) that the source image must have
            to be considered for mirroring. Only used when `image` does not contain a
            tag.
          required: false
          type: string
          default: ""
        maxver:
          description: |
            Maximum version (extracted from image tag) that the source image must have
            to be considered for mirroring. Only used when `image` does not contain a
            tag.
          required: false
          type: string
          default: ""

jobs:
  mirror:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ssakm
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Do mirror
        uses: amir28/gh-action-image-mirror@fix-multiplatform
        with:
          image: '${{ inputs.image }}'
          registry: '${{ inputs.registry }}'
          options: '${{ inputs.options }}'
          tags: '${{ inputs.tags }}'
          minver: '${{ inputs.minver }}'
          maxver: '${{ inputs.maxver }}'
